services:

  postgres:
    image: postgres:17
    container_name: weather-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weatherpass
      POSTGRES_DB: weather

    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather -d weather"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - weather-net

  api:
    build:
      context: .                  # La racine du projet est le point de départ
      dockerfile: ./api/Dockerfile # Où trouver le Dockerfile
    container_name: weather-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - weather-net

networks:
  weather-net:
    driver: bridge
